name = "ConvDiffMIPDECO"
uuid = "a5043af4-87b7-523b-a69b-dfae2487be3a"
license = "MIT"
desc = "MIPDECO solvers for source inversions in convection diffusion PDEs"
authors = ["Lars Ruthotto <lruthotto@emory.edu>"]
version = "0.0.1"

[compat]
julia = "0.7"

[deps]
KrylovMethods = "9a2cd570-f05c-5dc1-9209-93ad6f5727f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ParSpMatVec = "ccf9b6e2-7ea7-596a-9d65-09863b18e8cc"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
jInv = "3dacf901-f8cd-5544-86ed-7a705f85c244"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
